[package]
name = "well"
description = "chat with your codebase"
readme = "README.md"
repository = "https://github.com/xhjkl/well"
license = "MIT"
version = "0.0.0"
edition = "2021"
resolver = "2"

[dependencies]
colored = "2"
chrono = "0.4"
dotenvy = "0.15"
git2 = { version = "0.17", features = ["vendored-libgit2", "vendored-openssl"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.34", features = ["full"] }

tree-sitter = "0.20"
tree-sitter-python = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-typescript = "0.20"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = "fat"
strip = true
